storage:
    originals: F:\photos
    thumbs: G:\Photos\thumbs

converters:
    handbrake:
        executable: C:\Program Files\HandBrake\HandBrakeCLI.exe
        encoder: nvenc_h264
    ffmpeg:
        executable: C:\Program Files\ImageMagick-7.1.0-Q16-HDRI\ffmpeg.exe
    imagemagick: 
        executable: C:\Program Files\ImageMagick-7.1.0-Q16-HDRI\magick.exe

feeds:
    sftpaccounts:
    -   host: 192.168.1.10
        port: 2249
        rootfolder: /home/Photos/MobileBackup
        user: hui
        password: Simon2010!
    -   host: 192.168.1.10
        port: 2249
        rootfolder: /home/Photos/MobileBackup
        user: jelte
        password: wuyi555

network:
    public-url: https://www.projects.jeltechnologies.com/photos/
    local-nas-port: 8080
    
specialdaysprograms:
    days:
    -   name: sara-birthday
        label: Sara's birthday
        day: 22
        month: 5
        year: 2013  
    -   name: simon-birthday
        label: Simon's birthday
        day: 9
        month: 8
        year: 2010        
    -   name: hui-birthday
        label: Hui's birthday
        day: 10
        month: 6
        year: 1970
    -   name: jelte-birthday
        label: Jelte's birthday
        day: 26
        month: 11
        year: 1972
    -   name: wedding-day
        label: Wedding day
        day: 27
        month: 9
        year: 2003
    -   name: opa-birthday
        label: Opa's birthday
        day: 11
        month: 9
        year: 1944
    -   name: oma-birthday
        label: Oma's birthday
        day: 28
        month: 4
        year: 1943
    groups:
    -   name: family-birthdays
        label: Family birthdays
        days: sara-birthday, simon-birthday, hui-birthday, jelte-birthday
    -   name: extended-family-birthdays
        label: Extended birthdays
        days: sara-birthday, simon-birthday, hui-birthday, jelte-birthday,oma-birthday,opa-birthday

dimensioning:
    photo-threads: 5
    movie-threads: 2
    caching: true
    start-background-tasks-at-startup: true

show_live_photos: true
mapkey: pk.eyJ1Ijoiam92YWxsYTEyMzQiLCJhIjoiY2t3YXlua21mMGE0eTJucWtndXJkejAyaSJ9.gdaEVCODc7Hs9tBi76rGLg
